### PR TITLE
Frienship1

### PR DESCRIPTION
**Pull request by taiwo2**
In this milestone we are to meet the requirement below:
Create a model with associations and all requested features for friendships. Hint with spoiler alert: If you are stuck, read this article https://smartfunnycool.com/friendships-in-activerecord/.

IMPORTANT NOTE: In the next milestone, you will make friendships associations more efficient. In this one, let’s prepare the working version of the feature.

Remember about unit and integrations tests!

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
You did a commendable job in this PR. You have properly setup the project. A user can send requests to other users (via console) and users can confirm/delete friend requests from other users (via console), a user can also see the list of his friends (via console). This is a good direction for this project so far.
Let's make some crucial changes to the PR so we can merge.
- [ ] You currently don't have tests in this PR. Please add tests. The test cases should cover logic for sending/confirming/deleting friend requests, list one's friends list, etc
- [ ] Add a button for sending friend request to another user from the UI. Right now the only way to do that is via the console. 
- [ ] Add a button to confirm/delete friend requests from other users.
- [ ] Update the readme file by removing sections that do not have content. Right now you have `TBA` for sections that do not have relevant information to add. So remove the `Live demo`, and `Deployment` sections of the readme but add relevant content to the `Author`, `License` and `acknowledgements` sections. I believe you have the relevant information.

#### Note
- It's a good habit to commit often. Your PR has only three commits. This doesn't make sense given that a lot of work was put into this PR and many changes made. Committing often helps you to recover your work in case any happens out of your control.

### Martin Afani

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:full_moon:
**Hi Taiwo!
Nice one:clap::clap:. The app is working as expected. The project codebase is clean and easy to read. You are almost there:blush:. Just a few changes to make and the project will be approved:muscle:.**

**Mandatory requirements**

- [ ] Check if students added Unit and Integration tests! ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Currently there are no test in the project. Kindly add both positive and negative test case scenarios.

- [ ] Update the author section in the readme. 

Make the above-required changes and when you are ready, request another review.
 Kindly drop your questions:point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy Coding:blush:
Eric Enaburekhan

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required🛑♻**

<hr>

Hello there, good job working on the required changes to make the project meet its specifications. However, there are still few fixes that need to be implemented.

- [ ] First, please make sure that none of your tests is failing, currently there are 29 examples with 29 failures. Please fix them all.
- [ ] Second is (for easier accessing) Please make sure to add the "Invite" button on the users' all page too
user_can_see_invite_buttton

<hr>

- **[OPTIONAL]** Following the previous point, please add the "Accept" and "Reject" buttons under each user's name (only when there's a friend request send by them) on the users' all page as well.

<hr>

Kindly do the required changes and ask for another review.
Good luck and happy coding 👨‍💻💻

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
You have not made any changes requested by previous TSEs. Please work on them first before asking for a code review

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi @taiwo2**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
